// <auto-generated />
using System;
using FinancialOCR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancialOCR.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExtractedData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentLanguage");

                    b.HasIndex("DocumentType");

                    b.HasIndex("ProcessingStatus");

                    b.HasIndex("UploadedAtUtc");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ExtractedFinancialDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DetectedLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExtractionJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Gst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Hst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Pst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Qst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DetectedLanguage");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ExtractionJobId");

                    b.ToTable("ExtractedFinancialDocuments", (string)null);
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ExtractedLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ExtractedFinancialDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ExtractedFinancialDocumentId");

                    b.ToTable("ExtractedLineItems", (string)null);
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ExtractionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetectedLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("EstimatedProviderCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long?>("FallbackLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FallbackModelName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FallbackOcrEngine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FallbackProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("FallbackUsed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("OverallConfidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<long>("PrimaryLatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("PrimaryModelName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimaryOcrEngine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RawText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedDocumentLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarningsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DetectedLanguage");

                    b.HasIndex("DocumentId");

                    b.ToTable("ExtractionJobs", (string)null);
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ManualCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CorrectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrectedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CorrectedValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OriginalValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("ManualCorrections", (string)null);
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ProviderUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("ExtractionJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("InputBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("InputTokenCount")
                        .HasColumnType("int");

                    b.Property<long?>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("OutputBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("OutputTokenCount")
                        .HasColumnType("int");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ExtractionJobId");

                    b.HasIndex("ModelName");

                    b.HasIndex("OperationType");

                    b.HasIndex("ProviderName");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("ProviderUsageRecords", (string)null);
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ExtractedFinancialDocument", b =>
                {
                    b.HasOne("FinancialOCR.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinancialOCR.Domain.Entities.ExtractionJob", "ExtractionJob")
                        .WithMany("ExtractedFinancialDocuments")
                        .HasForeignKey("ExtractionJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("ExtractionJob");
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ExtractedLineItem", b =>
                {
                    b.HasOne("FinancialOCR.Domain.Entities.ExtractedFinancialDocument", "ExtractedFinancialDocument")
                        .WithMany("LineItems")
                        .HasForeignKey("ExtractedFinancialDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtractedFinancialDocument");
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ExtractionJob", b =>
                {
                    b.HasOne("FinancialOCR.Domain.Entities.Document", "Document")
                        .WithMany("ExtractionJobs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ManualCorrection", b =>
                {
                    b.HasOne("FinancialOCR.Domain.Entities.Document", "Document")
                        .WithMany("ManualCorrections")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ProviderUsageRecord", b =>
                {
                    b.HasOne("FinancialOCR.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialOCR.Domain.Entities.ExtractionJob", "ExtractionJob")
                        .WithMany()
                        .HasForeignKey("ExtractionJobId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Document");

                    b.Navigation("ExtractionJob");
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.Document", b =>
                {
                    b.Navigation("ExtractionJobs");

                    b.Navigation("ManualCorrections");
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ExtractedFinancialDocument", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("FinancialOCR.Domain.Entities.ExtractionJob", b =>
                {
                    b.Navigation("ExtractedFinancialDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
